"use client";
import{useEffect,useState}from"react";import{useRouter}from"next/navigation";
const API=process.env.NEXT_PUBLIC_API_URL||"";
const emptyProject={name:"",description:"",branch:"main",shell:"bash",enabled:true,steps:[],environment:[],member_ids:[]};
const emptyStep={name:"",step_type:"command",cwd:"~",command:"",enabled:true,timeout:3600,continue_on_error:false};
const stepTypeName:any={command:"执行命令",git_pull:"Git Pull",restart:"重启服务",health_check:"健康检查"};
const stepTypeHint:any={command:"执行自定义 Shell 命令",git_pull:"在项目目录拉取指定分支的最新代码",restart:"执行重启服务相关命令",health_check:"执行健康检查命令或 URL"};
export default function Edit(){const r=useRouter(),[id,setId]=useState<string|null>(null),[p,setP]=useState<any>(null),[users,setUsers]=useState<any[]>([]),[allowed,setAllowed]=useState<boolean|null>(null),[saving,setSaving]=useState(false),[error,setError]=useState(""),[dragging,setDragging]=useState<number|null>(null);
 useEffect(()=>{fetch(API+"/api/auth/me",{credentials:"include"}).then(async x=>{if(!x.ok){window.location.href="/";return null}const u=await x.json();if(u.role!=="admin"){setAllowed(false);return u}setAllowed(true);return u});const x=new URLSearchParams(window.location.search).get("id");setId(x);if(!x)setP({...emptyProject});fetch(API+"/api/users",{credentials:"include"}).then(x=>x.ok?x.json():[]).then(setUsers)},[]);
 useEffect(()=>{if(!id)return;fetch(API+"/api/projects/"+id,{credentials:"include"}).then(x=>x.ok?x.json():null).then(setP)},[id]);
 if(allowed===false)return <main className="wrap"><div className="card empty"><h1>无权限</h1><p>只有管理员可以修改项目配置。</p><a className="button-link" href="/projects">返回项目列表</a></div></main>;
 if(p===null)return <main className="wrap"><div className="card">加载项目配置中...</div></main>;
 const updateStep=(i:number,key:string,value:any)=>setP({...p,steps:p.steps.map((s:any,j:number)=>j===i?{...s,[key]:value}:s)});
 const moveStep=(i:number,d:number)=>{const next=i+d;if(next<0||next>=p.steps.length)return;const steps=[...p.steps];[steps[i],steps[next]]=[steps[next],steps[i]];setP({...p,steps})};
 const duplicateStep=(i:number)=>{const steps=[...p.steps];steps.splice(i+1,0,{...steps[i],name:steps[i].name?steps[i].name+"（副本）":"步骤副本"});setP({...p,steps})};
 const dropStep=(to:number)=>{if(dragging===null||dragging===to)return;const steps=[...p.steps],item=steps.splice(dragging,1)[0];steps.splice(to,0,item);setP({...p,steps});setDragging(null)};
 const validate=()=>{if(!p.name.trim())return"请填写项目名称";if(!p.branch.trim())return"请填写 Git 分支";for(let i=0;i<p.steps.length;i++){const s=p.steps[i];if(!s.name.trim())return"第 "+(i+1)+" 个步骤缺少名称";if(!s.cwd?.startsWith("~/"))return"第 "+(i+1)+" 个步骤的工作目录必须从 ~/ 开始";if(!Number.isFinite(Number(s.timeout))||Number(s.timeout)<1)return"第 "+(i+1)+" 个步骤的超时时间必须大于 0";if(s.step_type!=="git_pull"&&!s.command.trim())return"第 "+(i+1)+" 个步骤需要填写执行命令"}for(let i=0;i<p.environment.length;i++){const e=p.environment[i];if(!e.key.trim())return"第 "+(i+1)+" 个环境变量缺少 KEY"}return""};
 const toggleMember=(uid:number)=>setP({...p,member_ids:p.member_ids.includes(uid)?p.member_ids.filter((x:number)=>x!==uid):[...p.member_ids,uid]});
 const save=async()=>{const msg=validate();setError(msg);if(msg)return;setSaving(true);const url=id?API+"/api/projects/"+id:API+"/api/projects",method=id?"PUT":"POST",body={...p,steps:p.steps.map((s:any)=>{const{position,id,...v}=s;return v}),environment:p.environment.map((e:any)=>{const{id,...v}=e;return v})};const x=await fetch(url,{method,headers:{"Content-Type":"application/json"},credentials:"include",body:JSON.stringify(body)});setSaving(false);if(!x.ok){setError((await x.json()).detail||"保存失败");return}r.push("/projects")};
 const remove=async()=>{if(!id||!confirm("确定删除这个项目吗？"))return;const x=await fetch(API+"/api/projects/"+id,{method:"DELETE",credentials:"include"});if(x.ok)r.push("/projects");else setError((await x.json()).detail||"删除失败")};
 return <main className="wrap"><div className="topbar"><div className="brand"><div className="brand-mark">D</div><div><div className="brand-title">{id?"编辑项目":"创建项目"}</div><p>配置部署环境、执行步骤与敏感变量</p></div></div><div><a href="/projects">项目列表</a><a href="/deployments">部署记录</a></div></div>
 <div className="editor-layout"><div className="editor-main">
  <section className="card editor-section"><div className="section-heading"><div><span className="section-index">01</span><div><h2>基础信息</h2><p>项目名称、代码分支和执行 Shell。</p></div></div><span className={p.enabled?"badge enabled":"badge disabled"}>{p.enabled?"已启用":"已禁用"}</span></div><div className="form-grid"><div><label>项目名称</label><input value={p.name} placeholder="例如：官网前端" onChange={e=>setP({...p,name:e.target.value})}/></div><div><label>Git 分支</label><input value={p.branch} placeholder="main" onChange={e=>setP({...p,branch:e.target.value})}/></div><div className="full"><label>项目说明</label><input value={p.description} placeholder="简单描述这个项目的用途" onChange={e=>setP({...p,description:e.target.value})}/></div><div><label>Shell</label><select value={p.shell} onChange={e=>setP({...p,shell:e.target.value})}><option value="bash">bash</option><option value="zsh">zsh</option></select><small>部署时会使用对应 Shell 环境执行命令。</small></div><div className="toggle-box"><label><input className="check" type="checkbox" checked={p.enabled} onChange={e=>setP({...p,enabled:e.target.checked})}/> 启用项目</label><small>禁用后仍保留配置，但不会允许普通操作员部署。</small></div></div></section>
  <section className="card editor-section"><div className="section-heading"><div><span className="section-index">02</span><div><h2>部署步骤</h2><p>拖动步骤调整执行顺序，也可以复制已有步骤快速配置。</p></div></div><span className="badge">{p.steps.length} 个步骤</span></div>
   <div className="step-editor-list">{p.steps.map((s:any,i:number)=><div className={"step-editor "+(!s.enabled?"is-disabled ":"")+(dragging===i?"is-dragging":"")} key={i} draggable onDragStart={()=>setDragging(i)} onDragOver={e=>e.preventDefault()} onDrop={()=>dropStep(i)} onDragEnd={()=>setDragging(null)}>
    <div className="step-head"><span className="drag-handle" title="拖动排序">⠿</span><div className="step-number">{i+1}</div><div className="step-title"><strong>{s.name||"未命名步骤"}</strong><span>{stepTypeName[s.step_type]||s.step_type} · {stepTypeHint[s.step_type]||""}</span></div><div className="step-tools"><button type="button" className="icon-button secondary" disabled={i===0} onClick={()=>moveStep(i,-1)}>↑</button><button type="button" className="icon-button secondary" disabled={i===p.steps.length-1} onClick={()=>moveStep(i,1)}>↓</button><button type="button" className="icon-button secondary" onClick={()=>duplicateStep(i)}>复制</button><button type="button" className="icon-button danger" onClick={()=>setP({...p,steps:p.steps.filter((_:any,j:number)=>j!==i)})}>删除</button></div></div>
    <div className="step-grid"><div><label>步骤名称</label><input value={s.name} placeholder="例如：拉取最新代码" onChange={e=>updateStep(i,"name",e.target.value)}/></div><div><label>步骤类型</label><select value={s.step_type} onChange={e=>updateStep(i,"step_type",e.target.value)}><option value="command">执行命令</option><option value="git_pull">Git Pull</option><option value="restart">重启服务</option><option value="health_check">健康检查</option></select><small>{stepTypeHint[s.step_type]}</small></div><div><label>工作目录</label><input value={s.cwd} placeholder="~/project" onChange={e=>updateStep(i,"cwd",e.target.value)}/><small>必须从 ~/ 开始。</small></div><div><label>超时时间（秒）</label><input type="number" min="1" value={s.timeout} onChange={e=>updateStep(i,"timeout",Number(e.target.value))}/></div><div className="full"><label>{s.step_type==="health_check"?"Health Check URL":"执行命令"}</label><textarea className="code-input" value={s.command} disabled={s.step_type==="git_pull"} placeholder={s.step_type==="git_pull"?"Git Pull 步骤无需填写命令":"输入要执行的命令"} onChange={e=>updateStep(i,"command",e.target.value)}/></div></div><div className="step-options"><label><input className="check" type="checkbox" checked={s.enabled} onChange={e=>updateStep(i,"enabled",e.target.checked)}/> 启用此步骤</label><label><input className="check" type="checkbox" checked={s.continue_on_error} onChange={e=>updateStep(i,"continue_on_error",e.target.checked)}/> 失败后继续</label></div>
   </div>)}</div><button type="button" className="add-step" onClick={()=>setP({...p,steps:[...p.steps,{...emptyStep}]})}>＋ 添加部署步骤</button></section>
  <section className="card editor-section"><div className="section-heading"><div><span className="section-index">03</span><div><h2>部署权限</h2><p>选择可以执行该项目部署的操作员。管理员始终拥有全部项目权限。</p></div></div><span className="badge">{p.member_ids.length} 名操作员</span></div>{users.filter((u:any)=>u.role==="operator").length===0?<div className="permission-note">当前还没有操作员账号，请先在用户管理中创建操作员。</div>:<div className="member-list">{users.filter((u:any)=>u.role==="operator").map((u:any)=><label className={"member-option "+(p.member_ids.includes(u.id)?"selected":"")} key={u.id}><input className="check" type="checkbox" checked={p.member_ids.includes(u.id)} onChange={()=>toggleMember(u.id)}/><span className="member-avatar">{u.username.slice(0,1).toUpperCase()}</span><span><strong>{u.username}</strong><small>操作员</small></span></label>)}</div>}</section>
  <section className="card editor-section"><div className="section-heading"><div><span className="section-index">04</span><div><h2>环境变量</h2><p>为部署过程提供运行时环境变量，敏感变量不会明文展示。</p></div></div><span className="badge">{p.environment.length} 个变量</span></div><div className="env-list">{p.environment.map((e:any,i:number)=><div className="env-row" key={"env"+i}><div><input placeholder="KEY" value={e.key} onChange={x=>{e.key=x.target.value;setP({...p})}}/></div><div><input placeholder={e.is_secret?"留空则保留原密码":"VALUE"} type={e.is_secret?"password":"text"} value={e.value} onChange={x=>{e.value=x.target.value;setP({...p})}}/></div><label className="env-secret"><input className="check" type="checkbox" checked={e.is_secret} onChange={x=>{e.is_secret=x.target.checked;e.value="";setP({...p})}}/> 敏感</label><button type="button" className="icon-button danger" onClick={()=>setP({...p,environment:p.environment.filter((_:any,j:number)=>j!==i)})}>删除</button></div>)}</div><button type="button" className="secondary" onClick={()=>setP({...p,environment:[...p.environment,{key:"",value:"",is_secret:false}]})}>＋ 添加环境变量</button></section>
 </div><aside className="editor-sidebar"><div className="card sticky-card"><h3>配置摘要</h3><div className="summary-row"><span>项目状态</span><strong>{p.enabled?"已启用":"已禁用"}</strong></div><div className="summary-row"><span>执行 Shell</span><strong>{p.shell}</strong></div><div className="summary-row"><span>Git 分支</span><strong>{p.branch||"-"}</strong></div><div className="summary-row"><span>部署步骤</span><strong>{p.steps.length}</strong></div><div className="summary-row"><span>部署成员</span><strong>{p.member_ids.length}</strong></div><div className="summary-row"><span>环境变量</span><strong>{p.environment.length}</strong></div>{error&&<div className="editor-error">{error}</div>}<div className="save-panel"><button disabled={saving} onClick={save}>{saving?"保存中...":"保存项目"}</button><a className="button-link secondary" href="/projects">取消</a>{id&&<button className="danger" onClick={remove}>删除项目</button>}</div></div></aside></div></main>}
