"use client";
import{useEffect,useState}from"react";import{useRouter}from"next/navigation";
const API=process.env.NEXT_PUBLIC_API_URL||"";
function statusName(v:string){return v==="success"?"成功":v==="failed"?"失败":v==="cancelled"?"已取消":v==="running"?"运行中":v==="pending"?"等待中":v||"-"}
function time(v:string|null){return v?new Date(v).toLocaleString():"-"}
function duration(x:any){if(!x?.started_at)return"-";const end=x.finished_at?new Date(x.finished_at).getTime():Date.now(),sec=Math.max(0,Math.floor((end-new Date(x.started_at).getTime())/1000));return sec<60?sec+" 秒":Math.floor(sec/60)+" 分 "+sec%60+" 秒"}
export default function Projects(){const[p,setP]=useState<any[]>([]),[me,setMe]=useState<any>(null),[deployments,setDeployments]=useState<any[]>([]),[loading,setLoading]=useState(true),[deploying,setDeploying]=useState<number|null>(null);const r=useRouter();
 useEffect(()=>{Promise.all([fetch(API+"/api/projects",{credentials:"include"}),fetch(API+"/api/auth/me",{credentials:"include"}),fetch(API+"/api/deployments?page=1&page_size=100",{credentials:"include"})]).then(async([a,b,c])=>{if(a.status===401){r.push("/");return}const projects=await a.json();setP(projects);if(b.ok)setMe(await b.json());if(c.ok){const x=await c.json();setDeployments(x.items||[])}}).finally(()=>setLoading(false))},[]);
 const deploy=async(id:number)=>{setDeploying(id);const z=await fetch(API+"/api/projects/"+id+"/deploy",{method:"POST",credentials:"include"});setDeploying(null);if(!z.ok){alert((await z.json()).detail);return}const d=await z.json();r.push("/deployments?id="+d.id)};
 const latest=(id:number)=>deployments.find(x=>Number(x.project_id)===Number(id));const active=(id:number)=>deployments.find(x=>Number(x.project_id)===Number(id)&&(x.status==="running"||x.status==="pending"));
 return <main className="wrap"><div className="topbar"><div className="brand"><div className="brand-mark">D</div><div><div className="brand-title">项目管理</div><p>管理部署项目与执行配置</p></div></div><div><a href="/">首页</a><a href="/deployments">部署记录</a>{me?.role==="admin"&&<a href="/users">用户管理</a>}{me?.role==="admin"&&<button onClick={()=>r.push("/projects/edit")}>＋ 添加项目</button>}</div></div>
 <div className="projects-hero"><div><span className="hero-kicker">PROJECTS</span><h1>项目管理</h1><p>配置部署流程，查看项目运行状态并快速执行发布。</p></div><div className="project-summary"><div><strong>{p.length}</strong><span>全部项目</span></div><div><strong>{p.filter(x=>x.enabled).length}</strong><span>已启用</span></div><div><strong>{p.filter(x=>active(x.id)).length}</strong><span>执行中</span></div></div></div>
 <div className="section-title"><div><h2>全部项目</h2><span className="badge">{p.length} 个项目</span></div></div>
 {loading?<div className="card">加载项目状态中...</div>:<div className="grid">{p.map(x=>{const last=latest(x.id),run=active(x.id);return <div className="card project-card project-card-enhanced" key={x.id}><div className="project-card-top"><div className="project-icon">{x.name?.slice(0,1).toUpperCase()||"P"}</div><span className={x.enabled?"badge enabled":"badge disabled"}>{x.enabled?"已启用":"已禁用"}</span></div><h2>{x.name}</h2><p>{x.description||"暂无项目说明"}</p><div className="project-meta"><span className="badge">{x.shell}</span><span className="badge">{x.branch}</span><span className="badge">{x.steps?.length??"-"} 个步骤</span></div><div className={run?"project-running":"project-last"}>{run?<><span className="pulse-dot"></span><div><strong>部署正在执行</strong><small>部署 #{run.id} · {time(run.started_at||run.created_at)}</small></div></>:last?<><span className={"project-result "+last.status}>{last.status==="success"?"✓":last.status==="failed"?"!":"•"}</span><div><strong>最近部署：{statusName(last.status)}</strong><small>{time(last.started_at||last.created_at)} · {duration(last)}</small></div></>:<div><strong>尚未部署</strong><small>创建配置后即可开始部署</small></div>}</div><div className="project-actions">{me?.role==="admin"&&<button type="button" className="secondary" onClick={()=>r.push("/projects/edit?id="+x.id)}>编辑</button>}{(me?.role==="admin"||me?.role==="operator")&&<button type="button" disabled={!x.enabled||!!run||deploying===x.id} onClick={()=>deploy(x.id)}>{deploying===x.id?"启动中...":run?"部署中...":x.enabled?"立即部署":"项目已禁用"}</button>}{last&&<a className="button-link" href={"/deployments?id="+last.id}>查看</a>}</div></div>})}</div>}
 {!loading&&p.length===0&&<div className="card empty"><h3>暂无项目</h3><p>创建项目后，可以在这里统一管理部署。</p>{me?.role==="admin"&&<button onClick={()=>r.push("/projects/edit")}>创建项目</button>}</div>}
 </main>}
